//! `yunta schema`: the shape of a document Yunta reads and validates,
//! for whoever has to write one.
//!
//! This is the door for a shell — an agent working in a repo without the
//! control plane mounted, or a person writing the file by hand. Both had
//! nothing before it: the files under `schemas/` are generated by the
//! repository's own development tooling and never reach anyone who
//! installed the binary.
//!
//! The text is the same one a node's session receives and the
//! `document_shape` tool returns, from the same constant. Four doors
//! rendering four texts drift apart at the first schema change; four
//! doors rendering one do not.

use yunta_core::shape::{published, KINDS};
use yunta_core::DocumentKind;

use crate::error::{CliError, Outcome};

/// Prints one kind's shape, or lists the kinds when none is named.
pub fn schema(kind: Option<&str>, json: bool) -> Result<Outcome, CliError> {
    let Some(name) = kind else {
        if json {
            return Err(CliError::msg(
                "`--json` emits one document's schema: name a kind, or run `yunta schema` \
                 with no arguments to list them",
            ));
        }
        println!("{}", list());
        return Ok(Outcome::Success);
    };

    let kind = parse(name)?;
    if json {
        let schema = yunta_core::schema::for_kind(kind);
        let rendered = serde_json::to_string_pretty(&schema)
            .map_err(|error| CliError::msg(format!("cannot render the schema: {error}")))?;
        println!("{rendered}");
    } else {
        print!("{}", published(kind));
    }
    Ok(Outcome::Success)
}

fn parse(name: &str) -> Result<DocumentKind, CliError> {
    KINDS
        .into_iter()
        .find(|kind| kind.as_str() == name)
        .ok_or_else(|| {
            CliError::msg(format!(
                "`{name}` is not a document Yunta reads; one of {}",
                KINDS
                    .iter()
                    .map(|kind| format!("`{kind}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ))
        })
}

/// The catalog, one kind per line with what it is for.
fn list() -> String {
    let mut out = String::from("Documents Yunta reads and validates:\n");
    for kind in KINDS {
        out.push_str(&format!("  {:<12} {}\n", kind.as_str(), kind.label()));
    }
    out.push_str(
        "\nRun `yunta schema <kind>` for the shape to write, or add `--json` for the \
         JSON Schema an editor can validate against.",
    );
    out
}
